
---
apiVersion: v1
kind: Config
current-context: fb38b547trial
clusters:
- name: fb38b547trial
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1ekNDQWsrZ0F3SUJBZ0lSQU9sVm5FSzJGdVJlOUM3WUpOZllFSll3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpZd01UQXlNVE0wTmpRd1doY05Nell3TVRBeU1UTTBOelF3V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FhSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnR1BBRENDQVlvQ2dnR0JBSmRFCktrWjFJR2doM2MvZjZkekFaTE5FV0Fqb1JpVVl1ejJvR2hlQVo5d3M0aVVaQWNadE1pOHp3cXY2WkxDa2J4VGwKY1IxL2g1RnJaQnFQSzVac2VJRGtwYm45bXVQMDdKY3huR1RuK1lyU1BmUFgvclJQQjZTRFpocVBCZ0J0UHZTMgpvaWVkNnE0RHVYajRkb0RiTjdLb0taVzFPRXV2eitNNEtSWGxETTBxL0RVUUJoMVh3c0ZCaFhPZUk2d29BRHREClVSck9ydmpWaTZYSTRnK1gzYlZOdFJwbytqN3FtaTZvNmkvWEdLeisyVUh1bllhZVhkODZHb2FkbWsySVdDaFQKSE1MOGRmeVpzcmplZm0xSDRnYjhqaitKYi9EMml4MFp0b2w3dmVIUFJvNFk1TDEvUHQ1VW1pSktOaEJvYVRnNwp1VzF3WmhtMkg4ajhaMjNDemliZXdzSG92VW10SUZhdDY4UUNVT01HSEdid3FsRVhDQnU4NjlRU2tXeENwN1NpCmNsUWRDWmN0b1A0bUlscXZZY2VLQlFWTDFxQ1R5SWxYUGJ6bTk2OUZTaUQyWEJ1WDhTZFMvTy9aT1N2alpMS3EKK2FDaWwrSGtTT1hseHU5OGJFanNhQ1Aza2JWQmZuTTVybDNaRHpYOSs3SVZ0S1F3QjRzOVM0S3VuZHk5SHdJRApBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVV3QnlJMDY2Wk9JeS9qeFdzbGZITlBVUURZdWt3RFFZSktvWklodmNOQVFFTEJRQURnZ0dCQUliUWxuMEEKZzlNSmhBODRCYW01MFRPS3NSRExOZFJxZzFIeXVHbUtUVDF6N2JRSFJNTDkwNkR0T2FvS0J1OWF5UEVjRVVXUgpxNWhoSTJmSkpjOFBvKzlldXBURFlwMkxLUzlnQVdkdkl5eVBNQXMwQXE5cE9Zd3hheVVDWDEyNkhKNitzaytuCkNVWGJuSjVKNDZTYmxUYXl3SnBGcWhyenFGbUpsV0ZJMFg5Uy9HV3BnV3JFRWV4TTRjODNMMkJNTnVzYU0wM0YKa1dqUlZVcElncUpRbGc3R0dnM2VLT1dZQ0Fma2VjQ2MxelJ0ZDROZlNUSDR6OHpob0pVcFlvUHRxU3dmT1ZaYQoxQWxVVVVHNFZpQlI3Z2Q0TWV6ZWFNYnBGZVg5SFd0Z0J3L2RIWFR3WjRlUWJDQkt5OGhBanVkbDNaelQ2ak5QCk0zQVZyZkhHc2xlc29Ld3JlU3g4dGZDV0lHM0NrYzdVWG5xQWppVFZueVdyNlpLbUtRZEUvN01lbXFlNXp3WGgKZVlMVGwvYTc4N2ZEL0FTdm03dFowbURHZ25weUV2VjlKNGtaV2E4clVhQ2lRVERKd3NPaVNUcW9RZXVVbUMwdgpxVlZDV0JLZjdqZ283Tmt1NGl4WnUySFhDWS9qSFZnNXA1Qk1sNlh4SDNLaXVuSVJ2cjdyUmtlenNRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://api.c-178ca79.kyma.ondemand.com
contexts:
- name: fb38b547trial
  context:
    cluster: fb38b547trial
    user: fb38b547trial
users:
- name: fb38b547trial
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
